version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      MONGO_URL: 'mongodb://admin:admin@mongo:27017'
    ports:
      - '3000:3000'

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
